### PR TITLE
Update unicode combining table for py37.

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by ralphbean** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=1583600

**Comment by abadger** [comment]
Closing and reopening to try to trigger travis

**Comment by abadger** [comment]
@ralphbean I have the travis unittests passing now.  Go ahead and rebase this and see if it works in travis.  I'll add 3.7 testing in travis in another PR and see if I can replicate the failures seen iin https://bugzilla.redhat.com/show_bug.cgi?id=1583600 there

**Comment by abadger** [comment]
I needed the combining table update in order to pass on Python-3.7 so I rebased this and merged it.

**Pull request merged**
